### PR TITLE
Refactor upsert into entities

### PR DESCRIPTION
**Pull request by ericnormand**
This refactors the upsert functionality into the entities namespace.

### CODE REVIEW

**Comment by cap10morgan** [comment]
@tie-rack Should we merge this one (after scaling work lands)? Other than the private fns (I'd be in favor of making those public again), it seems like an OK change to me.

**Comment by tie-rack** [comment]
It looks like it would behave the same... but this seems to need to be written with `swap-tx!`. This is a race condition waiting to happen.

**Comment by cap10morgan** [comment]
@tie-rack Think we should close this one unmerged for now? And then maybe leave the branch around in case it's still a good basis for a future improvement?

**Comment by tie-rack** [comment]
@cap10morgan Sounds good. Closing.

**Pull request closed without merging**
